"""create ads schema

Revision ID: 505370026132
Revises: 
Create Date: 2026-09-23 18:00:21.850383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector



# revision identifiers, used by Alembic.
revision: str = '505370026132'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.String(length=100), nullable=False),
    sa.Column('campaign_name', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_campaign_id'), 'campaigns', ['campaign_id'], unique=True)
    op.create_index(op.f('ix_campaigns_platform'), 'campaigns', ['platform'], unique=False)
    op.create_table('ads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ad_id', sa.String(length=100), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('reach', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('spend', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('conversions', sa.Integer(), nullable=False),
    sa.Column('conversion_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('ctr', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('cpc', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('cpa', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('roas', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('audience', sa.String(length=255), nullable=True),
    sa.Column('age_group', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('device', sa.String(length=50), nullable=True),
    sa.Column('placement', sa.String(length=100), nullable=True),
    sa.Column('headline', sa.String(length=500), nullable=False),
    sa.Column('primary_text', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('call_to_action', sa.String(length=100), nullable=False),
    sa.Column('marketing_angle', sa.String(length=100), nullable=False),
    sa.Column('tone', sa.String(length=100), nullable=False),
    sa.Column('offer_type', sa.String(length=100), nullable=True),
    sa.Column('product_category', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ads_ad_id'), 'ads', ['ad_id'], unique=True)
    op.create_index(op.f('ix_ads_campaign_id'), 'ads', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_ads_date'), 'ads', ['date'], unique=False)
    op.create_index(op.f('ix_ads_marketing_angle'), 'ads', ['marketing_angle'], unique=False)
    op.create_index(op.f('ix_ads_platform'), 'ads', ['platform'], unique=False)
    op.create_table('ad_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ad_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', Vector(768), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ad_id'], ['ads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_documents_ad_id'), 'ad_documents', ['ad_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ad_documents_ad_id'), table_name='ad_documents')
    op.drop_table('ad_documents')
    op.drop_index(op.f('ix_ads_platform'), table_name='ads')
    op.drop_index(op.f('ix_ads_marketing_angle'), table_name='ads')
    op.drop_index(op.f('ix_ads_date'), table_name='ads')
    op.drop_index(op.f('ix_ads_campaign_id'), table_name='ads')
    op.drop_index(op.f('ix_ads_ad_id'), table_name='ads')
    op.drop_table('ads')
    op.drop_index(op.f('ix_campaigns_platform'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_campaign_id'), table_name='campaigns')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
